# Generated by Django 4.2.25 on 2025-10-07 11:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('BOOKMARKED', 'Bookmarked'), ('APPLYING', 'Applying'), ('APPLIED', 'Applied'), ('INTERVIEWING', 'Interviewing'), ('NEGOTIATING', 'Negotiating'), ('ACCEPTED', 'Accepted'), ('WITHDREW', 'Withdrew'), ('NOT_ACCEPTED', 'Not Accepted'), ('NO_RESPONSE', 'No Response'), ('ARCHIVED', 'Archived')], default='BOOKMARKED', max_length=32)),
                ('priority', models.IntegerField(default=3)),
                ('job_post_url', models.URLField(blank=True, null=True)),
                ('job_notes', models.TextField(blank=True, null=True)),
                ('date_deadline', models.DateField(blank=True, null=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('date_interviewed', models.DateField(blank=True, null=True)),
                ('date_offered', models.DateField(blank=True, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('date_accepted', models.DateField(blank=True, null=True)),
                ('date_rejected', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('pay_scale', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
