# Generated by Django 4.2.25 on 2025-10-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='pay_scale',
        ),
        migrations.AddField(
            model_name='company',
            name='founding_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='funding',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_nonprofit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='keywords',
            field=models.JSONField(blank=True, help_text='List of descriptive tags', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, choices=[('1-10', '1–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('201-500', '201–500'), ('501-1000', '501–1,000'), ('1001-2000', '1,001–2,000'), ('2001-5000', '2,001–5,000'), ('5001-10000', '5,001–10,000'), ('10001+', '10,001+')], help_text='Company size range by employee count', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits_perks',
            field=models.JSONField(blank=True, default=list, help_text='List of benefits/perks offered.'),
        ),
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.JSONField(blank=True, default=dict, help_text='Degree requirements and majors by level'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='licenses_certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='role_type',
            field=models.CharField(blank=True, choices=[('IC', 'Individual Contributor'), ('MANAGER', 'People Manager'), ('EXECUTIVE', 'Executive / Leadership')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('JPY', 'JPY'), ('OTHER', 'Other')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_raw',
            field=models.CharField(blank=True, help_text='Unparsed salary text from job post', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='security_clearances',
            field=models.JSONField(blank=True, default=list, help_text='List of applicable security clearance levels.'),
        ),
        migrations.AddField(
            model_name='job',
            name='shifts_and_schedules',
            field=models.JSONField(blank=True, default=dict, help_text='Shift, schedule, and availability details for the job.'),
        ),
        migrations.AddField(
            model_name='job',
            name='travel_requirements',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
