# Generated by Django 4.2.25 on 2025-10-09 09:57

from django.db import migrations, models
import django.db.models.deletion
import jobs.models.attachment
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_company_options_remove_job_pay_scale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('resume', 'Resume'), ('job_details', 'Job Details'), ('other_document', 'Other Document')], default='other_document', help_text='Categorize this file as a resume, job details, or other document.', max_length=32)),
                ('file', models.FileField(help_text='Upload a PDF, Markdown (.md), or Text (.txt) file.', upload_to='attachments/', validators=[jobs.models.attachment.validate_file_type])),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.job')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
