# Generated by Django 4.2.25 on 2025-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('resume', 'Resume'), ('job_details', 'Job Details'), ('job_post', 'Job Post'), ('other_document', 'Other Document')], default='other_document', help_text='Categorize this file as a resume, job details, or other document.', max_length=32),
        ),
    ]
